### PR TITLE
Fixes utf8.charpattern in Lua 5.1

### LINKED ISSUE #218: utf8.charpattern is not compatible with Lua 5.1
In the UTF8 module, a charpattern [is defined](https://github.com/keplerproject/lua-compat-5.3/blob/master/lutf8lib.c#L235). This pattern uses `\0`; however, this is not a valid pattern in Lua 5.1.

From the [manual](http://www.lua.org/manual/5.1/manual.html#5.4.1):
> A pattern cannot contain embedded zeros. Use %z instead. 

The compat library has a work-round for this. It patches the pattern [in its Lua module.](https://github.com/keplerproject/lua-compat-5.3/blob/master/compat53/module.lua#L48-L58)

In Luvi, this module [is loaded](https://github.com/luvit/luvi/blob/master/src/luvi_compat.c#L31) without this patch. We need to implement this somehow. Either by patching it in C or in Lua.

### PR DESCRIPTION
**Pull request by SinisterRectus**
Closes #218 

I decided to fix this directly in the C file. Note that `lua_pop` was only called once after requiring the utf8 module. I don't know if this does anything practical, but if it's necessary, I also added a pop for the string module.

Also note that this file seems to mix functions from different Lua versions:

- `luaL_register` is unique to 5.1. It was deprecated in 5.2 in favor of `luaL_setfuncs`.
- `luaL_requiref` was added in 5.2. I guess this is made possible by the presence of the 5.3-compat library.

### CODE REVIEW

File: src/luvi_compat.c [hunk 1]
```diff
@@ -27,8 +34,16 @@ void luvi_openlibs(lua_State *L) {
...
   }
+  lua_pop(L, 1);
 
   luaL_requiref(L, LUA_UTF8LIBNAME, luaopen_utf8, 1);
+
+#if (LUA_VERSION_NUM == 501)
+
+  lua_pushlstring(L, UTF8PATT_501, sizeof(UTF8PATT_501)/sizeof(char) - 1);
+  lua_setfield(L, -2, "charpattern");
   lua_pop(L, 1);
```
Comment (squeek502) [inline src/luvi_compat.c:45]: This pop should be outside of the `#if`, since its popping the value from `luaL_requiref`, right?

Comment (SinisterRectus) [reply src/luvi_compat.c:45]: Yep.

**Review by squeek502 — APPROVED** [review]
